sudo: required
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
language: node_js
node_js:
  - "8.9.1"
script: ./scripts/travis/build.sh && ./scripts/travis/test.sh

